version: 2.1

orbs:
  change-api: financial-times/change-api@1.0.6

references:
  filter_only_main: &filter_only_main
    branches:
      only: main
  filter_ignore_main: &filter_ignore_main
    branches:
      ignore: main

jobs:
  toxify:
      docker:
        - image: python:3.8
      steps:
        - checkout
        - run: pip install tox && tox

workflows:
  run-tests:
    jobs:
      - toxify:
          filters:
            <<: *filter_ignore_main
  
  run-tests-trigger-change-api:
    jobs:
      - toxify:
          filters:
            <<: *filter_only_main
      - change-api/change-log:
            context: change-api-orb
            system-code: 'nodejsscan-orb'
            environment: 'prod'
            slack-channels: 'cyber-security-alerts'
            requires:
                - toxify
            filters:
                <<: *filter_only_main
